title: TechExcel Sentinel onboarding
description: The goal of this lab is to practice configuring an environment designed for managing Windows and Linux security events in Azure Sentinel.
theme: just-the-docs

aux_links:
  "TechExcel: Sentinel onboarding and migration acceleration (level 300 / CSU) lab": 
    - "https://github.com/microsoft/TechExcel-Sentinel-onboarding-and-migration-acceleration/"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red
